baseurl: "https://github.com/iankloo/course_site_demo/blob/main/docs/"
publishDir: "docs"
languageCode: en-us
title: SE375 Course Website
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Syllabus
      url: /syllabus.pdf
    - name: Course Calendar
      url: /calendar.pdf
    - name: Booking AI
      url: https://outlook.office365.com/owa/calendar/KlooAI@westpoint.edu/bookings/
    - name: Stats Concepts
      url: /stats_concepts/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: SE375 Course Website.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
